---
# Server LAMP installation and configuration
- hosts: 
  remote_user: root
  vars: 
    omeka_db_host:      "localhost" 
    omeka_db_username:  "omeka"
    omeka_db_password:  "omeka_password"
    omeka_db_name:      "omeka"
    omeka_db_prefix:    "omeka_"
    email:              "admin@youdomain"
    default_from_email: "do-not-reply@yourdomain"
    default_from_name:  "yourdomain Administrator"
  
  tasks:
#    - include: tasks/server_setup.yml
    - include: tasks/omeka_deploy.yml
