---
# Server LAMP installation and configuration
- hosts: com
  remote_user: root
  
  tasks:
    - name: Install epel repo
      yum: name={{ item }} state=present
      with_items:
        - epel-release
        - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
          
    - name: Update the server prior to installing lamp
      shell: 'yum -y update'

    - name: Install webstack and database to run php-application.
      yum: name={{ item }} state=present
      with_items:
        - htop
        - ImageMagick 
        - httpd 
        - httpd-devel 
        - libmemcached 
        - libmemcached-devel 
        - links 
        - memcached 
        - memcached-devel 
        - mod_auth_mysql 
        - mod_ssl 
        - mod_wsgi 
        - mysql 
        - mysql-devel 
        - mysql-server 
        - pcre-devel 
        - php 
        - php-cli 
        - php-common 
        - php-devel 
        - php-gd 
        - php-mbstring 
        - php-mcrypt 
        - php-mysql  
        - php-pear 
        - php-pecl-memcache 
        - php-pecl-memcached 
        - php-xml 
        - php-zts 
        - php-fpm
        - php-enchant
        - git
        - git-all
        - unison240
        - vim 
        - wget
