---
# Server LAMP installation and configuration
- hosts: :
  remote_user: root
  vars_prompt:
    fqdn: "define it's fully qualified domain name eg mySite.com"
    project_name: "what is the projects name"
  
  vars:
    mysql_host: "localhost"
  
  tasks:
    - include: tasks/new_domain.yml
 
