---
##############################################################
#   initial setup of appache 
#   set up will accomplish creating
#   /websites directory
#   /etc/httpd/conf/virtual_hosts directory
#   
#   disable mod_php so that we can use it as a cgi
# ############################################################

- name: Setup default Websites and virtual_hosts directory directory
  file: 
    path: {{ item.path }}
    mode: 0644
  with_items:
    - { path: '/websites', mode: 0644 }
    - { path: '/etc/httpd/conf/virtual_hosts', mode: 0655 }


- name: Disable the apache module mod_php
  apache2_module: state=absent name=mod_php

- name: Configure httpd.conf
  lineinfile:
    dest: '/etc/httpd/conf/httpd.conf'
    regexp: {{ item.regexp }}
    line:  {{ item.line }}
  with_items:
    - { regexp: 'DocumentRoot "/var/www/html"',       line: 'DocumentRoot /websites' }
    - { regexp: 'Directory "/var/www/html"',          line: 'Dicrectory "/websites"' }
    - { regexp: 'AllowOverride None',                 line: 'AllowOverride All' }
    - { regexp: 'Order allow,deny' ,                  line: 'Order deny,allow' }
    - { regexp: 'Allow from all',                     line: 'Deny from All' }
    - { regexp: 'DirectoryIndex',                     line: 'DirectoryIndex index.php' }
    - { regexp: '#NameVirtualHost',                   line: 'NameVirtualHost'   } 
    - { regexp: '#Include conf/virtual_hosts/*.conf', line: 'Include conf/virtual_hosts/*.conf' }
