---
##############################################################
#   initial setup of appache 
#   set up will accomplish creating
#   /websites directory
#   /etc/httpd/conf/virtual_hosts directory
#   
#   disable mod_php so that we can use it as a cgi
# ############################################################

- name: Setup default Websites and virtual_hosts directory directory
  file: 
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - { path: '/websites', mode: '0644' }
    - { path: '/etc/httpd/conf/virtual_hosts', mode: '0655' }

- name: Check if php.conf exists
  stat: path=/etc/httpd/conf.d/php.conf
  register: php_conf

- name: Disable the apache module mod_php
  command: mv php.conf php chdir=/etc/httpd/conf.d 
  when: php_conf.stat.exists


