---
##seting up default directory variables
- name: Set virtual hoss folder location
  command: echo "/etc/httpd/conf/virtual_hosts"
  register: virtual_hosts

- name: set db host
  command: echo "mysql.localdomain"
  register: mysql_host
  
- name: Create Random password
  command: cat /dev/urandom | tr -cd "[:alnum:]" | head -c 25
  register: password

- name: set websites directory
  command: echo "/websites"
  register: websites


- name: create project folders
  raw: mkdir -p /websites/{{ project_name }}/{home,www,var/phpsessions}
  
- name: Save the password to file
  command: echo "dbuser: {{ project_name }} dbpasswd: {{ password }}" > /websites/{{ project_name }}/home/mysqlinfo
  
- name: Create the project user and group.
  user: name={{ project_name }} comment={{ fqdn }} groups=projects shell=/bin/false home="/websites/{{ project_name }}/home"

- name: Create the projects sftp user
  user: name={{ project_name }}_sftp comment="SFTP user for {{ fqdn }}" groups=sftponly,{{ project_name }} shell=/bin/false home="/websites/{{ project_name }}"
   

- name: Create the virtual hosts configuration file
  template: src=./templates/virtual_host.j2 dest=/etc/httpd/conf/virtual_hosts/{{ project_name }}.conf
  
- name: Create php-fpm configuration file
  template: src=./templates/php-fpm.conf.j2 dest=/etc/php-fpm.d/{{ project_name }}.conf

- name: Copy phpfix file into projects var directory
  copy: src=./phpfix dest=/websites/{{ project_name }}/var/phpfix
  
- name: Create the projects database
  mysql_db: name={{ project_name }} state=present
  
- name: Create the database user
  mysql_user: name={{ project_name }} password={{ password }} priv={{ project_name }}.*:ALL host={{ mysql_host }}
