---
- name: Get a timestamp for the file 
  command: date +%Y%m%d%H%M%S
  register: timestamp

- name: set the releases variable
  command: echo "/webdata/omeka/releases/{{ timestamp.stdout }}"
  register: releases


- name: Install or update repo
  git: 
    repo: "{{ item.r }}" 
    dest: "{{ item.d }}" 
    version: "{{ item.v }}" 
    update: yes
    accept_hostkey: true
  with_items:
    - { r: 'https://github.com/omeka/Omeka.git', d: '{{ releases.stdout }}',  v: 'master' }


- name: Install Or update Plugins
  git: 
    repo: "https://github.com/omeka/plugin-{{ item.repo }}.git" 
    dest: "{{ releases.stdout }}/plugins/{{ item.repo }}" 
    version: "{{ item.version }}"
    update: yes        
    accept_hostkey: true
  with_items:
   - { repo: 'Coins',             version: 'ece0d1b8f4838852d8ca8fcb9f944dd5e1e870b4' }
   - { repo: 'CollectionTree',    version: '2e34f4c7c26dc3a6aaadd1412a8fdc52e3992ad1' }
   - { repo: 'Commenting',        version: '7478dd21ee4118f0a9f7e3c6f78bd825bf218fa1' }
   - { repo: 'CSSEditor',         version: '440647f154c632f387150496bc45ce481c0aaf0e' }
   - { repo: 'CsvImport',         version: '178b01d4a6a1b59037521110234ca4466dcc838d' }
   - { repo: 'Dropbox',           version: 'dd35d114c9de19a6db941c85623856b6f3c11b37' }
   - { repo: 'ExhibitBuilder',    version: '47da937c921ea5b64ee05636bee574da1c46c9a7' }
   - { repo: 'Geolocation',       version: '280c37a502051c03122e65e51d9ecf0e37b00eaa' }
   - { repo: 'ItemRelations',     version: '13e7b3d4f288db03e707fc825955b30b784ec53a' }
   - { repo: 'LcSuggest',         version: 'd16773c86d6e9a8a182ce3ed4a71dc517b77de0b' }
   - { repo: 'PdfText',           version: 'c89d055d6ac390d7f315ad19ef9d0b9037f76a28' }
   - { repo: 'RedactElements',    version: '7691eb474f79b0d36ed878a868444f5017fe0386' }
   - { repo: 'Reports',           version: 'e10a1a001a6f419ea5ac4c3b17c089b17d5d90d9' }
   - { repo: 'SearchByMetadata',  version: '8f59244bfd07c4e68d509412eed297268e1e8abb' }
   - { repo: 'SimpleContactForm', version: 'b8613e1d5e38cae7f8541d0573e3c297af9ee851' }
   - { repo: 'SimplePages',       version: '076c17d3d9c9d8416d5475c665f7f094d9bd1845' }

- name: Install Html5Media
  git:
    repo: "https://github.com/omeka/{{ item.repo }}.git"
    dest: "{{ releases.stdout }}/plugins/{{ item.repo }}"
    version: "{{ item.version }}"
    update: yes
    accept_hostkey: true
  with_items:
   - { repo: 'Html5Media', version: 'v2.3'}

- name: Install or update themes
  git:
    repo: "https://github.com/omeka/theme-{{ item.repo }}.git" 
    dest: "{{ releases.stdout }}/themes/{{ item.repo }}" 
    version: "{{ item.version }}"
    update: yes 
    accept_hostkey: true
  with_items:
  - { repo: 'berlin', version: '033671d434eef0ee4791e3b3b927eb669ef8a51d' }
  - { repo: 'emiglio', version: 'af8fee7e7e37d55850629b05809f76fe431248f1' }
  - { repo: 'minimalist', version: '1b7311ebdd25fa122d47c289bc73817bb13e6134' }
  - { repo: 'rhythm', version: 'aae2c1da5ae8ca68319741981ada2fce4d562995' }
  - { repo: 'santa-fe', version: '5a84db884403a24161b97bbfbe8d8fae44474d83' }
  - { repo: 'seasons', version: 'c9fe202d25ea86c2cd7064c48ad6531be5dae7da' }

- name: install or update default theme (thanksroy)
  git:
    repo: "https://github.com/omeka/theme-{{ item.repo }}.git" 
    dest: "{{ releases.stdout }}/themes/default" 
    version: "{{ item.version }}"
    update: yes 
    accept_hostkey: true
  with_items:
     - { repo: 'thanksroy',     version: '498e13060988b720752239778f5231196c46308e' }


- name: Copy htaccess
  raw: cp {{ releases.stdout }}/.htaccess.changeme {{ releases.stdout }}/.htaccess
    
- name: Copy create the errors.log file
  raw:  touch {{ releases.stdout }}/application/logs/errors.log

- name: Add config.ini to config folder 
  template: src=./templates/config.ini.j2 dest={{ releases.stdout }}/application/config/config.ini owner=omeka group=omeka mode=0644    
   
- name: fill in db.ini
  template: src=./templates/db.ini.j2 dest={{ releases.stdout }}/db.ini owner=omeka group=omeka mode=0644

- name: Remove files folder
  raw: rm -fr {{ releases.stdout }}/files
  
- name: Create the link to the files folder
  file: src=/webdata/omeka/files dest={{ releases.stdout }}/files owner=omeka group=omeka state=link

- name: change www owner adn group
  raw: chown -R omeka:omeka /webdata/omeka

- name: Unlink old www folder
  raw: rm -fr /webdata/omeka/www

- name: Link the new release
  file: src={{ releases.stdout }} dest=/webdata/omeka/www owner=omeka group=omeka state=link
