---
- name: Check if the www folder exists 
  stat: path=/webdata/omeka/www
  register: not_initial_commit
  
- name: Get a timestamp for the file 
  command: date +%Y%m%d%H%M%S
  register: timestamp
  
- name: If this is not the initial commit mv www folder to archive
  command: mv /webdata/omeka/www /webdata/omeka/archive/{{ timestamp.stdout }} 
  when: not_initial_commit.stat.exists

- name: Install or update repo
  git: 
    repo: "{{ item.r }}" 
    dest: "{{ item.d }}" 
    version: "{{ item.v }}" 
    update: yes
  with_items:
    - { r: 'https://github.com/omeka/Omeka.git', d: '/webdata/omeka/www',  v: 'v2.3' }


- name: Install Or update Plugins
  git: 
    repo: "https://github.com/omeka/plugin-{{ item.repo }}.git" 
    dest: "/webdata/omeka/www/plugins/{{ item.repo }}" 
    version: "{{ item.version }}"
    update: yes        
  with_items:
     - { repo: 'Coins',             version: 'v2.0.3' }
     - { repo: 'CollectionTree',    version: 'v2.0.2' }
     - { repo: 'Commenting',        version: 'v2.1.2' }
     - { repo: 'CSSEditor',         version: 'v1.0.1' }
     - { repo: 'CsvImport',         version: 'v2.0.3' }
     - { repo: 'Dropbox',           version: 'v0.7.2' }
     - { repo: 'ExhibitBuilder',    version: 'v3.1.3' }
     - { repo: 'Geolocation',       version: 'v2.2.3' }
     - { repo: 'ItemRelations',     version: 'v2.0.2' }
     - { repo: 'LcSuggest',         version: 'v2.0'   }
     - { repo: 'PdfText',           version: 'v1.0'   }
     - { repo: 'RedactElements',    version: 'master' }
     - { repo: 'Reports',           version: 'v2.0.1' }
     - { repo: 'SearchByMetadata',  version: 'v1.2'   }
     - { repo: 'SimpleContactForm', version: 'v0.5'   }
     - { repo: 'SimplePages',       version: 'v3.0.4' }
     
- name: Install or update themes
  git:
    repo: "https://github.com/omeka/theme-{{ item.repo }}.git" 
    dest: "/webdata/omeka/www/themes/{{ item.repo }}" 
    version: "{{ item.version }}"
    update: yes 
  with_items:
     - { repo: 'thanksroy',  version: 'v2.2.1' }
     - { repo: 'berlin',     version: 'v2.2.1' }
     - { repo: 'emiglio',    version: 'v2.0.3' }
     - { repo: 'minimalist', version: 'v2.0.1' }
     - { repo: 'rhythm',     version: 'v2.0.1' }
     - { repo: 'santa-fe',   version: 'v2.0.1' }
     - { repo: 'seasons',    version: 'v2.2.1' }

- name: Copy htaccess, configfiles
  raw: cp /webdata/omeka/www/.htaccess.changeme /webdata/omeka/www/.htaccess
    
- name: Copy htaccess, configfiles
  raw: cp /webdata/omeka/www/application/config/config.ini.changeme /webdata/omeka/www/application/config/config.ini
    
   
- name: fill in db.ini
  template: src=./templates/db.ini.j2 dest=/webdata/omeka/www/db.ini owner=omeka group=omeka mode=0644

- name: change www owner adn group
  raw: chown omeka:omeka /webdata/omeka/www
